### ISSUE TITLE
Failure if parent of --html_dir does not exist

### ISSUE THREAD

**Issue by stefanct** [noseglasses/elf_diff#115]
**Describe the bug**
If the parent directory of the one specified by `--html_dir` does not exist, execution fails (see log at the end).
If the directory is created manually beforehand execution works fine.

**To Reproduce**
1. Make sure the output directory to be specified by `--html_dir` and its parent does not exist.
2. Run `elf_diff --html_dir parentdir/htmldir ...` 

**Expected behavior**
The directory including all leading components should be created.

**Desktop (please complete the following information):**
 - OS: Debian 12, fresh venv with only pip and elf_diff (0.7.1) installed (incl. prerequisites)

**Additional context**

[elf_diff.log](https://github.com/noseglasses/elf_diff/files/14619374/elf_diff.log)

**Comment by noseglasses** [comment]
@stefanct, thank you very much for reporting this. The problem should now be fixed in latest master.

**Comment by noseglasses** [comment]
Closing issue. Feel free to reopen if necessary.
